services:
  web:
    image: httpd:2.4
    ports: 
      - "9000:80"
    volumes:
      - ../dist:/usr/local/apache2/htdocs
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: on-failure

