services:
  web:
    image: httpd:2.4
    ports: 
      - "127.0.0.1:9090:80"
    volumes:
      - ../dist:/usr/local/apache2/htdocs
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: on-failure
  11ty:
    image: femtopixel/eleventy
    volumes:
      - ..:/app
    entrypoint: ["eleventy", "--serve"]
