name: Build and Deploy TEI Website
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
  repository_dispatch:
    types: [update-documentation]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'
      - name: Update submodule
        run: git submodule update --remote src/documentation/Documentation
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Set up analytics
        run: cp src/_includes/analytics.html_src src/_includes/analytics.html
      - name: Build
        run: |
          npm install
          npx @11ty/eleventy
      - name: Deploy
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEIWEB_KEY }}
      - run: |
          ssh -o StrictHostKeyChecking=accept-new ${{ secrets.TEIWEB_USER }}@${{ secrets.TEIWEB_HOST }} uptime
          rsync -avz -e ssh --delete dist/ ${{ secrets.TEIWEB_USER }}@${{ secrets.TEIWEB_HOST }}:${{ secrets.TEIWEB_PATH }}