name: Build and Deploy TEI Website
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - ".docker/**"
  repository_dispatch:
    types: [update-documentation]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          submodules: 'recursive'
      - name: Update submodule
        run: git submodule update --remote src/documentation/Documentation

      # Login to DockerHub registry
      - name: Log in to DockerHub
        uses: docker/login-action@v4
        with:
          # username and password are set in GitHub secrets
          username: ${{ secrets.PETERS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PETERS_DOCKERHUB_TOKEN }}

      # Login to dh.io registry
      - name: Log in to DockerHub
        uses: docker/login-action@v4
        with:
          registry: dhi.io
          # username and password are set in GitHub secrets
          username: ${{ secrets.PETERS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PETERS_DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            teic/website
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=dhi.io/httpd:2.4-debian
